-- Run this entire file once in Supabase Dashboard -> SQL Editor.
create type public.user_role as enum ('customer', 'kitchen_owner', 'rider');
create type public.order_status as enum ('pending', 'accepted', 'rejected', 'preparing', 'ready', 'awaiting_rider', 'rider_assigned', 'picked_up', 'delivered');
create type public.rating_type as enum ('kitchen', 'rider');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'customer', name text not null default '', phone text not null default '', address text not null default '', latitude double precision, longitude double precision, current_lat double precision, current_lng double precision, wallet_balance numeric(12,2) not null default 1000.00 check (wallet_balance >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.kitchens (id uuid primary key default gen_random_uuid(), owner_id uuid not null unique references public.profiles(id) on delete cascade, name text not null, address text not null, latitude double precision, longitude double precision, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.menu_items (id uuid primary key default gen_random_uuid(), kitchen_id uuid not null references public.kitchens(id) on delete cascade, name text not null, description text, price numeric(12,2) not null check(price > 0), image_url text, is_available boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id), kitchen_id uuid not null references public.kitchens(id), rider_id uuid references public.profiles(id), status public.order_status not null default 'pending', final_price numeric(12,2) not null check(final_price > 0), platform_fee numeric(12,2) not null default 0, rider_fee numeric(12,2) not null default 0, delivery_address text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, menu_item_id uuid not null references public.menu_items(id), quantity integer not null check(quantity > 0), unit_price numeric(12,2) not null check(unit_price > 0), created_at timestamptz not null default now());
create table public.chats (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete cascade, created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), chat_id uuid not null references public.chats(id) on delete cascade, sender_id uuid not null references public.profiles(id), text text not null check(length(trim(text)) > 0), created_at timestamptz not null default now());
create table public.ratings (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, rated_user_id uuid not null references public.profiles(id), rated_by_user_id uuid not null references public.profiles(id), rating_type public.rating_type not null, stars smallint not null check(stars between 1 and 5), review_text text, created_at timestamptz not null default now(), unique(order_id, rating_type));
create index orders_customer_idx on public.orders(customer_id); create index orders_kitchen_idx on public.orders(kitchen_id); create index orders_rider_idx on public.orders(rider_id); create index menu_items_kitchen_idx on public.menu_items(kitchen_id); create index messages_chat_idx on public.messages(chat_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id, role, name, phone, address) values (new.id, coalesce((new.raw_user_meta_data->>'role')::public.user_role, 'customer'), coalesce(new.raw_user_meta_data->>'name',''), coalesce(new.raw_user_meta_data->>'phone',''), coalesce(new.raw_user_meta_data->>'address','')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger profiles_updated before update on public.profiles for each row execute procedure public.set_updated_at(); create trigger kitchens_updated before update on public.kitchens for each row execute procedure public.set_updated_at(); create trigger menu_items_updated before update on public.menu_items for each row execute procedure public.set_updated_at(); create trigger orders_updated before update on public.orders for each row execute procedure public.set_updated_at();
alter table public.profiles enable row level security; alter table public.kitchens enable row level security; alter table public.menu_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.chats enable row level security; alter table public.messages enable row level security; alter table public.ratings enable row level security;
create policy "profiles readable" on public.profiles for select to authenticated using (true); create policy "users update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid()); create policy "kitchens readable" on public.kitchens for select to authenticated using (true); create policy "owners manage kitchen" on public.kitchens for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid()); create policy "menu readable" on public.menu_items for select to authenticated using (true); create policy "owners manage menu" on public.menu_items for all to authenticated using (exists(select 1 from public.kitchens k where k.id = kitchen_id and k.owner_id = auth.uid())) with check (exists(select 1 from public.kitchens k where k.id = kitchen_id and k.owner_id = auth.uid())); create policy "orders visible to participants" on public.orders for select to authenticated using (customer_id = auth.uid() or rider_id = auth.uid() or exists(select 1 from public.kitchens k where k.id = kitchen_id and k.owner_id = auth.uid())); create policy "customers create orders" on public.orders for insert to authenticated with check (customer_id = auth.uid());
